--[[
DISCLAIMER THIS SCRIPT WAS GENERATED BY AI IF I EVER PUBLISH THIS KNOW THAT IT IS NOT MY WORK AND IT IS ENTIRELY FOR PERSONAL USE.
I NEITHER CLAIM THIS AS MY OWN NOR OWN THIS SCRIPT.
--]]

filein = io.open("MorseCodeCopyPasta.txt", "r")
if not filein then return nil end

content = filein:read("*all")
filein:close()

local modifiedContent = string.gsub(content, " / ", "\n")

fileout = io.open("MorseCodeOut.txt", "w")
if fileout then
    fileout:write(modifiedContent)
    fileout:close()
end